import bitcoin from "assets/icons/main/bitcoin.png";
import chart from "assets/icons/main/chart.svg";

export const TYPES = [
  { id: 0, title: "All" },
  { id: 1, title: "Crypto" },
  { id: 2, title: "Stock" },
  { id: 3, title: "Index" },
];

export const RISKS = [
  { id: 0, title: "All" },
  { id: 1, title: "Very_high" },
  { id: 2, title: "High" },
  { id: 3, title: "Moderate" },
  { id: 4, title: "Low" },
];

export const WEATHERS = [
  { id: 0, title: "All" },
  { id: 1, title: "Sunny" },
  { id: 2, title: "Partly_cloudy" },
  { id: 3, title: "Mostly_cloudy" },
  { id: 4, title: "Rainy" },
  { id: 5, title: "Thunderstorm" },
  { id: 6, title: "Hurricane" },
  { id: 7, title: "Volcano" },
];

export const LOCATIONS = [
  { id: 0, title: "All" },
  { id: 1, title: "United States" },
  { id: 2, title: "Taiwan" },
  { id: 3, title: "Switzerland" },
  { id: 4, title: "China" },
  { id: 5, title: "Netherlands" },
  { id: 6, title: "Korea (South)" },
  { id: 7, title: "United Kingdom" },
  { id: 8, title: "France" },
  { id: 9, title: "Australia" },
  { id: 10, title: "Japan" },
  { id: 11, title: "Hongkong" },
  { id: 12, title: "Canada" },
  { id: 13, title: "Germany" },
  { id: 14, title: "India" },
  { id: 15, title: "Spain" },
  { id: 16, title: "Brazil" },
  { id: 17, title: "Belgium" },
  { id: 18, title: "Italy" },
  { id: 19, title: "Sweden" },
  { id: 20, title: "Norway" },
  { id: 21, title: "Saudi Arabia" },
  { id: 22, title: "South Africa" },
  { id: 23, title: "Ireland" },
  { id: 24, title: "Mexico" },
  { id: 25, title: "Finland" },
  { id: 26, title: "Indonesia" },
  { id: 27, title: "Singapore" },
  { id: 28, title: "Qatar" },
  { id: 29, title: "Kuwait" },
  { id: 30, title: "United Arab Emirates" },
  { id: 31, title: "Denmark" },
  { id: 32, title: "Israel" },
  { id: 33, title: "Austria" },
  { id: 34, title: "New Zealand" },
  { id: 35, title: "Peru" },
  { id: 36, title: "Philippines" },
  { id: 37, title: "Poland" },
  { id: 38, title: "Hungary" },
  { id: 39, title: "Colombia" },
  { id: 40, title: "Chile" },
  { id: 41, title: "Greece" },
  { id: 42, title: "Russian Federation" },
];

export const EXCHAGNES = [
  { id: 0, title: "All" },
  { id: 1, title: "Ethereum" },
  { id: 2, title: "Klaytn" },
  { id: 3, title: "TRON" },
  { id: 4, title: "BNB" },
  { id: 5, title: "NASDAQ" },
  { id: 6, title: "Russell 2000" },
  { id: 7, title: "NYSE COMPOSITE" },
  { id: 8, title: "KOSPI" },
  { id: 9, title: "S&P/TSX Composite" },
  { id: 10, title: "FTSE 100" },
  { id: 11, title: "Nikkei 225" },
  { id: 12, title: "DAX" },
  { id: 13, title: "Hangseng" },
  { id: 14, title: "NIFTY 50" },
  { id: 15, title: "IBEX 35" },
  { id: 16, title: "IBOVESPA" },
  { id: 17, title: "AEX" },
  { id: 18, title: "BEL 20" },
  { id: 19, title: "FTSE MIB" },
  { id: 20, title: "OMX Nordic 40" },
  { id: 21, title: "Oslo Bors Benchmark" },
  { id: 22, title: "JSE Limited" },
  { id: 23, title: "ISEQ All Share" },
  { id: 24, title: "Bolsa Mexicana De Valores" },
  { id: 25, title: "OMX Helsinki 25" },
  { id: 26, title: "IDX COMPOSITE" },
  { id: 27, title: "Singapore Exchange Ltd" },
  { id: 28, title: "Abu Dhabi Securities Exchange" },
  { id: 29, title: "OMX Copenhagen" },
  { id: 30, title: "CBOE Volatility Index" },
  { id: 31, title: "Austrian Traded Index" },
  { id: 32, title: "S&P/NZX 50" },
  { id: 33, title: "PSEI" },
  { id: 34, title: "WIG20" },
  { id: 35, title: "Budapest Stock Exchange" },
  { id: 36, title: "KLCI" },
  { id: 37, title: "TSEC weighted index" },
  { id: 38, title: "Bolsa de Valores de Colombia" },
  { id: 39, title: "S&P IPSA" },
  { id: 40, title: "Hellenic Exchanges" },
  { id: 41, title: "MOEX" },
  { id: 42, title: "Tadawul All Shares" },
  { id: 43, title: "Qatar Exchange" },
  { id: 44, title: "Kuwait Stock Exchange" },
  { id: 45, title: "Tel Aviv Stock Exchange Ltd." },
  { id: 46, title: "DFM General" },
  { id: 47, title: "TSEC" },
  { id: 48, title: "Euronext N.V." },
  { id: 49, title: "S&P/ASX 200" },
];

export const SECTROS = [
  { id: 0, title: "All" },
  { id: 1, title: "Information Technology" },
  { id: 2, title: "Consumer Discretionary" },
  { id: 3, title: "Communication" },
  { id: 4, title: "Health Care" },
  { id: 5, title: "Energy" },
  { id: 6, title: "Consumer Staples" },
  { id: 7, title: "Materials" },
  { id: 8, title: "Utilities" },
  { id: 9, title: "Industrials" },
  { id: 10, title: "Real Estate" },
];

export const VIEWS = [
  { id: 0, title: 20 },
  { id: 1, title: 50 },
  { id: 2, title: 100 },
];

export const EXPLORES = [
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,
    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,
    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,
    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,
    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,
    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,
    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,
    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,
    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,
    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,
    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,
    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,
    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,
    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,
    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,
    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 0,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 1,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 2,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 3,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 4,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 5,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 6,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 7,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 8,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 9,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 50,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 10,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 11,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 60.5,

    chartImage: chart,
    weatherIcon: "sharplyFalling",
    weather: "Sharply Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 12,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 70.5,

    chartImage: chart,
    weatherIcon: "maintaining",
    weather: "Maintaining",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 13,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 80.8,

    chartImage: chart,
    weatherIcon: "slightlyRising",
    weather: "Slightly Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 14,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 60,

    chartImage: chart,
    weatherIcon: "sharplyRising",
    weather: "Sharply Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 15,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "VeryHigh",
    maximumLoss: 90.1,

    chartImage: chart,
    weatherIcon: "extremelyRising",
    weather: "Extremely Rising",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 16,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "High",
    maximumLoss: 79.2,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 17,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Moderate",
    maximumLoss: 90.6,

    chartImage: chart,
    weatherIcon: "explosion",
    weather: "Risk of Explosion",
    price: 61942.2,
    priceChange: "2.99%",
  },
  {
    id: 18,
    image: bitcoin,
    name: "Bitcoin",
    subName: "BTC-USD",
    risk: "Low",
    maximumLoss: 48.3,

    chartImage: chart,
    weatherIcon: "slightlyFalling",
    weather: "Slightly Falling",
    price: 61942.2,
    priceChange: "2.99%",
  },
];
